### ISSUE TITLE
ImportError: cannot import name 'LikePath' from 'clickgen.util'

### ISSUE THREAD

**Issue by yochananmarqos** [ful1e5/Bibata_Cursor_Rainbow#1]
A user of my `bibata-rainbow-cursor-theme` AUR package [reported](https://aur.archlinux.org/packages/bibata-rainbow-cursor-theme/#comment-799242) this and I can reproduce it:

```
==> Starting build()...
Traceback (most recent call last):
  File "/build/bibata-rainbow-cursor-theme/src/Bibata_Cursor_Rainbow-1.1.0/builder/build.py", line 7, in <module>
    from brbpkg.configure import get_config
  File "/build/bibata-rainbow-cursor-theme/src/Bibata_Cursor_Rainbow-1.1.0/builder/brbpkg/configure.py", line 6, in <module>
    from brbpkg.extra import PNGProvider
  File "/build/bibata-rainbow-cursor-theme/src/Bibata_Cursor_Rainbow-1.1.0/builder/brbpkg/extra.py", line 14, in <module>
    from clickgen.util import LikePath
ImportError: cannot import name 'LikePath' from 'clickgen.util' (/usr/lib/python3.9/site-packages/clickgen/util.py)
```

It builds fine with `python-clickgen` 1.1.8.
